# Generated by Django 5.0.3 on 2024-03-16 10:17

from django.db import migrations

from ..operations import CreateAdjustedTxidCurrentFunction, CreateTxidOffsetFunction


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        CreateTxidOffsetFunction(),
        CreateAdjustedTxidCurrentFunction(),
    ]
