# Generated by Django 5.0.3 on 2024-03-17 13:56

from django.db import migrations

from tracked_model.operations import BackfillModelVersion


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0002_add_tracking"),
    ]

    operations = [
        BackfillModelVersion(tracked_model="MyModel"),
    ]
